import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import './globals.css';
import HeaderComponent from '@/components/common/header';
import FooterComponent from '@/components/common/footer';

const workSans = Work_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Umurava skills challenge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} text-primary antialiased`}>
        <HeaderComponent />
        <main className="overflow-x-hidden">{children}</main>
        <FooterComponent />
      </body>
    </html>
  );
}
